- name: exec docker script
  shell: /tmp/get-docker.sh
  notify: install docker compose

  
- name: install docker compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

